
# Use python as its the simplest language which can run a test script
language: python

before_install:
  # Print out the bash version
  - sudo /bin/bash --version
  # Install dependencies
  - sudo apt-get install shunit2
  # Remove this troublesome script
  - sudo rm /etc/profile.d/phpenv.sh

# Create a minecraft user for testing
install:
	- sudo adduser --system minecraft

# Run the test script
script: sudo /bin/bash ./test.sh

branches:
	only:
		- master